package net.runelite.api;

/** Stub of RuneLite's ChatMessageType. */
public enum ChatMessageType
{
	GAMEMESSAGE,
	MODCHAT,
	PUBLICCHAT,
	PRIVATECHAT,
	ENGINE,
	LOGINLOGOUTNOTIFICATION,
	PRIVATECHATOUT,
	MODPRIVATECHAT,
	FRIENDSCHAT,
	FRIENDSCHATNOTIFICATION,
	TRADE_SENT,
	BROADCAST,
	SNAPSHOTFEEDBACK,
	ITEM_EXAMINE,
	NPC_EXAMINE,
	OBJECT_EXAMINE,
	FRIENDNOTIFICATION,
	IGNORENOTIFICATION,
	CLAN_CHAT,
	CLAN_MESSAGE,
	CLAN_GUEST_CHAT,
	CLAN_GUEST_MESSAGE,
	AUTOTYPER,
	MODAUTOTYPER,
	CONSOLE,
	TRADEREQ,
	TRADE,
	CHALREQ_TRADE,
	CHALREQ_FRIENDSCHAT,
	SPAM,
	PLAYERRELATED,
	TENSECTIMEOUT,
	WELCOME,
	CLAN_CREATION_INVITATION,
	CHALREQ_CLANCHAT,
	CLAN_GIM_FORM_GROUP,
	CLAN_GIM_GROUP_WITH,
	CLAN_GIM_CHAT,
	CLAN_GIM_MESSAGE,
	DIALOG,
	MESBOX,
	NPC_SAY,
	DIDYOUKNOW,
	LEVELUPMESSAGE,
	UNKNOWN;

	public int getType()
	{
		return 0;
	}

	public static ChatMessageType of(int type)
	{
		return UNKNOWN;
	}
}
