package net.runelite.api;

/** Stub of RuneLite's (deprecated) InventoryID enum. */
@Deprecated
public enum InventoryID
{
	FISHING_TRAWLER_REWARD,
	TRADE,
	TRADEOTHER,
	INVENTORY,
	EQUIPMENT,
	BANK,
	PUZZLE_BOX,
	BARROWS_REWARD,
	MONKEY_MADNESS_PUZZLE_BOX,
	DRIFT_NET_FISHING_REWARD,
	KINGDOM_OF_MISCELLANIA,
	CHAMBERS_OF_XERIC_CHEST,
	THEATRE_OF_BLOOD_CHEST,
	SEED_VAULT,
	GROUP_STORAGE,
	GROUP_STORAGE_INV,
	WILDERNESS_LOOT_CHEST,
	TOA_REWARD_CHEST,
	LUNAR_CHEST,
	FORTIS_COLOSSEUM_REWARD_CHEST;

	public int getId()
	{
		return 0;
	}
}
