package net.runelite.api;

/** Stub of RuneLite's MenuAction. */
public enum MenuAction
{
	@Deprecated
	ITEM_USE_ON_GAME_OBJECT,
	WIDGET_TARGET_ON_GAME_OBJECT,
	GAME_OBJECT_FIRST_OPTION,
	GAME_OBJECT_SECOND_OPTION,
	GAME_OBJECT_THIRD_OPTION,
	GAME_OBJECT_FOURTH_OPTION,
	GAME_OBJECT_FIFTH_OPTION,
	@Deprecated
	ITEM_USE_ON_NPC,
	WIDGET_TARGET_ON_NPC,
	NPC_FIRST_OPTION,
	NPC_SECOND_OPTION,
	NPC_THIRD_OPTION,
	NPC_FOURTH_OPTION,
	NPC_FIFTH_OPTION,
	@Deprecated
	ITEM_USE_ON_PLAYER,
	WIDGET_TARGET_ON_PLAYER,
	@Deprecated
	ITEM_USE_ON_GROUND_ITEM,
	WIDGET_TARGET_ON_GROUND_ITEM,
	GROUND_ITEM_FIRST_OPTION,
	GROUND_ITEM_SECOND_OPTION,
	GROUND_ITEM_THIRD_OPTION,
	GROUND_ITEM_FOURTH_OPTION,
	GROUND_ITEM_FIFTH_OPTION,
	WALK,
	WIDGET_TYPE_1,
	WIDGET_TARGET,
	WIDGET_CLOSE,
	WIDGET_TYPE_4,
	WIDGET_TYPE_5,
	WIDGET_CONTINUE,
	@Deprecated
	ITEM_USE_ON_ITEM,
	WIDGET_USE_ON_ITEM,
	ITEM_FIRST_OPTION,
	ITEM_SECOND_OPTION,
	ITEM_THIRD_OPTION,
	ITEM_FOURTH_OPTION,
	ITEM_FIFTH_OPTION,
	@Deprecated
	ITEM_USE,
	WIDGET_FIRST_OPTION,
	WIDGET_SECOND_OPTION,
	WIDGET_THIRD_OPTION,
	WIDGET_FOURTH_OPTION,
	WIDGET_FIFTH_OPTION,
	PLAYER_FIRST_OPTION,
	PLAYER_SECOND_OPTION,
	PLAYER_THIRD_OPTION,
	PLAYER_FOURTH_OPTION,
	PLAYER_FIFTH_OPTION,
	PLAYER_SIXTH_OPTION,
	PLAYER_SEVENTH_OPTION,
	PLAYER_EIGHTH_OPTION,
	CC_OP,
	WIDGET_TARGET_ON_WIDGET,
	SET_HEADING,
	WORLD_ENTITY_FIRST_OPTION,
	WORLD_ENTITY_SECOND_OPTION,
	WORLD_ENTITY_THIRD_OPTION,
	WORLD_ENTITY_FOURTH_OPTION,
	WORLD_ENTITY_FIFTH_OPTION,
	RUNELITE_WIDGET,
	RUNELITE_HIGH_PRIORITY,
	EXAMINE_OBJECT,
	EXAMINE_NPC,
	EXAMINE_ITEM_GROUND,
	EXAMINE_ITEM,
	CANCEL,
	CC_OP_LOW_PRIORITY,
	EXAMINE_WORLD_ENTITY,
	RUNELITE,
	RUNELITE_OVERLAY,
	RUNELITE_OVERLAY_CONFIG,
	RUNELITE_PLAYER,
	RUNELITE_INFOBOX,
	RUNELITE_LOW_PRIORITY,
	UNKNOWN;

	public static final int MENU_ACTION_DEPRIORITIZE_OFFSET = 2000;

	public int getId()
	{
		return 0;
	}

	public static MenuAction of(int id)
	{
		return UNKNOWN;
	}
}
